<?php


class Log extends \Fuel\Core\Log {
//
//    public static function _init() {
//        parent::_init(); // TODO: Change the autogenerated stub
//        static::chromeHandler();
//    }
//
//    public static function chromeHandler() {
//        $stream = (new Monolog\Handler\ChromePHPHandler());
//        static::$monolog->pushHandler($stream);
//    }
}